In [20]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd. set_option("display.max_columns", None)
%matplotlib inline
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix



In [2]:
df_data=pd.read_csv('feat_25.csv')

In [3]:
df_data.head()

Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0    2.635364   -0.304088   -1.543373    0.626779   -1.274464    2.004415   
1    1.296154   -0.721865    0.072174    0.792741   -1.086483   -0.612700   
2    1.525916   -0.600327    0.888153   -0.938027   -2.587087   -0.828671   
3    1.873367   -0.009268    1.933797   -0.494299    1.302262   -1.368107   
4    1.876098   -0.611675    1.493026   -1.576377   -1.931573   -0.834816   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0    2.632512   -0.357011    0.922301   -0.476381    -0.679394     0.845453   
1    0.892532   -1.096112   -1.216686    1.014303    -2.064474    -0.759082   
2   -0.647110   -1.114573    0.438973   -1.142408    -0.253257     0.024593   
3    0.876166    1.714779   -0.336721    0.127624    -0.159981    -1.202945   
4   -0.851659   -0.670840    0.740518   -1.304296    -0.559495     0.052864   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0    -1.620134     1.271039     0.232265    -0.610930    -1.540198   
1    -0.656331    -1.070139     0.926862    -0.112256     0.642093   
2     0.232901    -1.213998    -1.542672     0.402928    -0.788130   
3    -1.578440     1.088574     1.495203     0.430647    -0.671202   
4    -1.214895    -0.972922    -0.675875    -0.496011     0.453942   

   Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20  Unnamed: 21  \
0     0.394365    -1.250810     0.035356    -0.938941    -0.157161   
1     1.253564    -0.778490    -1.254446     0.130718    -0.330290   
2    -0.964493     3.330313    -0.890775    -0.751055    -0.944583   
3     0.584147    -1.498880    -0.130008     0.426312     0.000161   
4    -0.641921     2.515081    -0.339636    -0.710988    -0.648390   

   Unnamed: 22  Unnamed: 23  Unnamed: 24  label  
0    -0.544130     1.417567     0.972746      0  
1    -0.617679    -0.219169     0.272224      0  
2     0.016899     0.093836    -0.204122      0  
3    -0.658402    -0.704637     0.073824      0  
4     0.857998    -0.653816    -0.006759      0

In [4]:
df_data.shape

(3000, 26)

In [5]:
df=df_data.iloc[:,:25]
label=df_data['label']

In [6]:
df.shape

(3000, 25)

In [7]:
label.shape

(3000,)

In [46]:
#from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="Pandas Profiling Report")

In [48]:
#profile.to_widgets()

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df, label, test_size=0.3, random_state=1, stratify = label)# stratify to avoid class imbalancing

## Check data for null values and missing values

In [9]:
df.isnull().sum() ## No missing values

Unnamed: 0     0
Unnamed: 1     0
Unnamed: 2     0
Unnamed: 3     0
Unnamed: 4     0
Unnamed: 5     0
Unnamed: 6     0
Unnamed: 7     0
Unnamed: 8     0
Unnamed: 9     0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
Unnamed: 14    0
Unnamed: 15    0
Unnamed: 16    0
Unnamed: 17    0
Unnamed: 18    0
Unnamed: 19    0
Unnamed: 20    0
Unnamed: 21    0
Unnamed: 22    0
Unnamed: 23    0
Unnamed: 24    0
dtype: int64

In [10]:
df.describe()

Unnamed: 0    Unnamed: 1    Unnamed: 2    Unnamed: 3    Unnamed: 4  \
count  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03   
mean   9.333398e-12 -1.200072e-11 -2.999987e-12  3.335091e-13 -4.999722e-12   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -1.789960e+00 -2.587950e+00 -2.754130e+00 -2.805608e+00 -2.749827e+00   
25%   -7.141050e-01 -7.390432e-01 -7.193058e-01 -7.290563e-01 -6.595378e-01   
50%   -9.943716e-02 -1.670179e-01  1.871209e-02 -3.923929e-02  9.490169e-03   
75%    5.807810e-01  7.664326e-01  6.804315e-01  6.612353e-01  6.577557e-01   
max    3.663638e+00  2.864353e+00  3.338261e+00  3.195516e+00  3.178566e+00   

         Unnamed: 5    Unnamed: 6    Unnamed: 7    Unnamed: 8    Unnamed: 9  \
count  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03   
mean  -2.333411e-12 -6.666686e-12  1.333233e-12 -2.000000e-12 -9.999332e-13   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -2.876071e+00 -2.659996e+00 -2.821675e+00 -3.080074e+00 -3.163819e+00   
25%   -6.790280e-01 -7.167174e-01 -7.348636e-01 -7.067961e-01 -7.171446e-01   
50%   -4.440216e-03 -3.527061e-02 -4.581859e-02 -1.986053e-02 -3.047797e-02   
75%    7.058558e-01  6.957528e-01  6.752356e-01  7.068385e-01  6.911088e-01   
max    3.018672e+00  3.597421e+00  3.028321e+00  4.040440e+00  3.231087e+00   

        Unnamed: 10   Unnamed: 11   Unnamed: 12   Unnamed: 13   Unnamed: 14  \
count  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03   
mean  -2.666638e-12 -6.666620e-12 -4.666559e-12  1.333284e-12 -5.999767e-12   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -3.235814e+00 -3.156153e+00 -3.122306e+00 -2.941533e+00 -3.135634e+00   
25%   -6.878024e-01 -7.035210e-01 -6.874863e-01 -6.929013e-01 -6.932000e-01   
50%   -5.533375e-03  3.740955e-04  2.034273e-02 -1.186078e-02 -4.696543e-02   
75%    6.522880e-01  6.699540e-01  6.642587e-01  6.963931e-01  6.961344e-01   
max    3.490582e+00  3.478944e+00  3.410029e+00  3.227656e+00  3.667908e+00   

        Unnamed: 15   Unnamed: 16   Unnamed: 17   Unnamed: 18   Unnamed: 19  \
count  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03   
mean  -2.999858e-12 -7.333148e-12 -3.334322e-13 -6.665099e-13  1.999843e-12   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -3.336436e+00 -3.279918e+00 -2.983516e+00 -3.434211e+00 -3.126884e+00   
25%   -6.421310e-01 -6.942895e-01 -6.821080e-01 -6.146073e-01 -6.943959e-01   
50%    6.317654e-02 -1.191983e-02 -2.023014e-02 -1.875957e-02 -1.554155e-02   
75%    6.521265e-01  6.438933e-01  6.788460e-01  6.431246e-01  6.477815e-01   
max    4.095312e+00  3.579468e+00  3.672507e+00  3.615591e+00  4.026558e+00   

        Unnamed: 20   Unnamed: 21   Unnamed: 22   Unnamed: 23   Unnamed: 24  
count  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  3.000000e+03  
mean  -6.999956e-12  2.000027e-12  3.666752e-12  8.999963e-12 -1.400001e-11  
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  
min   -3.637037e+00 -3.596098e+00 -3.784783e+00 -3.309904e+00 -3.602464e+00  
25%   -6.512388e-01 -6.295880e-01 -6.622247e-01 -6.961082e-01 -5.839969e-01  
50%    1.389252e-02 -1.541484e-03 -4.105993e-02 -4.400202e-02  2.738101e-02  
75%    6.549277e-01  6.313171e-01  6.475680e-01  6.381031e-01  6.255014e-01  
max    4.919712e+00  4.121440e+00  4.196466e+00  3.677125e+00  4.038517e+00

In [11]:
df.columns ## all are object data type 

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

## Linear kernel

In [12]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'linear', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Training set score: 0.9252
Test set score: 0.8833
[[88  0  0  0  1  1  0  0  0  0]
 [ 0 87  1  1  0  0  1  0  0  0]
 [ 2  0 78  1  1  1  3  1  1  2]
 [ 2  0  7 68  0  8  2  1  2  0]
 [ 0  0  0  0 82  1  2  0  0  5]
 [ 1  0  0 11  4 71  3  0  0  0]
 [ 0  1  0  0  0  0 89  0  0  0]
 [ 0  0  1  0  3  1  0 77  1  7]
 [ 0  4  2  6  0  5  2  0 70  1]
 [ 0  0  0  0  4  2  0  2  0 82]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96        90
           1       0.95      0.97      0.96        90
           2       0.88      0.87      0.87        90
           3       0.78      0.76      0.77        90
           4       0.86      0.91      0.89        90
           5       0.79      0.79      0.79        90
           6       0.87      0.99      0.93        90
           7       0.95      0.86      0.90        90
           8       0.95      0.78      0.85        90
           9       0.85      0.91      0.88        90

    accuracy           

## RBF kernel

In [14]:
# Feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Train the model; We will train different models using different value of C
svm = SVC(kernel= 'rbf', random_state=1, C=0.051,gamma='scale')
svm.fit(X_train_std, y_train)
 
# Measure accuracy score
y_pred = svm.predict(X_test_std)
#('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))
#The smaller the value of C, the wider the margins – which may lead to more misclassifications.
##Inversely, the larger the value of C, the more narrow the margins of the classifier become – this may lead to fewer misclassifications
# but higher values of c leads to overfitting
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Training set score: 0.8905
Test set score: 0.8700
[[83  0  0  0  1  5  1  0  0  0]
 [ 0 84  1  1  0  0  1  0  3  0]
 [ 0  1 79  2  2  2  1  0  2  1]
 [ 0  2 10 69  0  4  1  1  1  2]
 [ 0  1  0  0 78  2  0  0  1  8]
 [ 0  0  0  5  0 85  0  0  0  0]
 [ 1  0  2  0  0  4 83  0  0  0]
 [ 0  0  1  1  4  1  0 77  1  5]
 [ 0  3  1  4  0 15  0  0 65  2]
 [ 0  1  0  2  4  0  0  2  1 80]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95        90
           1       0.91      0.93      0.92        90
           2       0.84      0.88      0.86        90
           3       0.82      0.77      0.79        90
           4       0.88      0.87      0.87        90
           5       0.72      0.94      0.82        90
           6       0.95      0.92      0.94        90
           7       0.96      0.86      0.91        90
           8       0.88      0.72      0.79        90
           9       0.82      0.89      0.85        90

    accuracy           

## Polynomial kernel

In [15]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8,gamma='scale')
svclassifier.fit(X_train, y_train)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('Training set score: {:.4f}'.format(svm.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(svm.score(X_test, y_test)))

[[83  0  0  0  1  5  1  0  0  0]
 [ 0 84  1  1  0  0  1  0  3  0]
 [ 0  1 79  2  2  2  1  0  2  1]
 [ 0  2 10 69  0  4  1  1  1  2]
 [ 0  1  0  0 78  2  0  0  1  8]
 [ 0  0  0  5  0 85  0  0  0  0]
 [ 1  0  2  0  0  4 83  0  0  0]
 [ 0  0  1  1  4  1  0 77  1  5]
 [ 0  3  1  4  0 15  0  0 65  2]
 [ 0  1  0  2  4  0  0  2  1 80]]
              precision    recall  f1-score   support

           0       0.99      0.92      0.95        90
           1       0.91      0.93      0.92        90
           2       0.84      0.88      0.86        90
           3       0.82      0.77      0.79        90
           4       0.88      0.87      0.87        90
           5       0.72      0.94      0.82        90
           6       0.95      0.92      0.94        90
           7       0.96      0.86      0.91        90
           8       0.88      0.72      0.79        90
           9       0.82      0.89      0.85        90

    accuracy                           0.87       900
   macro avg       

## Cross validation with scikit learn

In [22]:
from sklearn.model_selection import cross_val_score
clf = SVC(kernel='rbf', C=1, random_state=42)
scores_params1 = cross_val_score(clf, df, label, cv=5)
scores_params1

array([0.94166667, 0.96166667, 0.96      , 0.94666667, 0.95666667])

In [23]:
clf = SVC(kernel='rbf', C=2, random_state=42)
scores_params2 = cross_val_score(clf, df, label, cv=5)
scores_params2 ## we got a metric to evaluate the performance for a specified hyper parameter.

array([0.95      , 0.96666667, 0.95333333, 0.94833333, 0.96333333])

In [40]:
def check(num1,num2):
    sum=0
    
    while num1<=num2:
        lst=str(num1)
       
        for i in range(len(lst)-1):
            
            flag=False
            if abs(int(lst[i+1])-int(lst[i]))==1:
                   flag=True
            else:
                flag=False
                break
                
                   
                    
        if flag==True:
                   sum+=int(num1)
        num1+=1
    return sum            

In [43]:
check(123,456)

4119

In [10]:
num1

NameError: name 'num1' is not defined